spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          # This should point to the Supabase Dev Project
          issuer-uri: https://moljpfoetpxwnrykvsxq.supabase.co/auth/v1
          jwk-set-uri: https://moljpfoetpxwnrykvsxq.supabase.co/auth/v1/.well-known/jwks.json
          audiences: authenticated

logging:
  level:
    root: INFO
    org.springframework.security: INFO
