package com.devlife4me.projectvital.model.enums;

import lombok.Getter;

@Getter
public enum CountryCode {
    AF("AF", "004", "Afghanistan"),
    AL("AL", "008", "Albania"),
    DZ("DZ", "012", "Algeria"),
    AS("AS", "016", "American Samoa"),
    AD("AD", "020", "Andorra"),
    AO("AO", "024", "Angola"),
    AI("AI", "660", "Anguilla"),
    AQ("AQ", "010", "Antarctica"),
    AG("AG", "028", "Antigua and Barbuda"),
    AR("AR", "032", "Argentina"),
    AM("AM", "051", "Armenia"),
    AW("AW", "533", "Aruba"),
    AU("AU", "036", "Australia"),
    AT("AT", "040", "Austria"),
    AZ("AZ", "031", "Azerbaijan"),
    BS("BS", "044", "Bahamas"),
    BH("BH", "048", "Bahrain"),
    BD("BD", "050", "Bangladesh"),
    BB("BB", "052", "Barbados"),
    BY("BY", "112", "Belarus"),
    BE("BE", "056", "Belgium"),
    BZ("BZ", "084", "Belize"),
    BJ("BJ", "204", "Benin"),
    BM("BM", "060", "Bermuda"),
    BT("BT", "064", "Bhutan"),
    BO("BO", "068", "Bolivia"),
    BA("BA", "070", "Bosnia and Herzegovina"),
    BW("BW", "072", "Botswana"),
    BR("BR", "076", "Brazil"),
    BN("BN", "096", "Brunei Darussalam"),
    BG("BG", "100", "Bulgaria"),
    BF("BF", "854", "Burkina Faso"),
    BI("BI", "108", "Burundi"),
    KH("KH", "116", "Cambodia"),
    CM("CM", "120", "Cameroon"),
    CA("CA", "124", "Canada"),
    CV("CV", "132", "Cape Verde"),
    KY("KY", "136", "Cayman Islands"),
    CF("CF", "140", "Central African Republic"),
    TD("TD", "148", "Chad"),
    CL("CL", "152", "Chile"),
    CN("CN", "156", "China"),
    CO("CO", "170", "Colombia"),
    KM("KM", "174", "Comoros"),
    CG("CG", "178", "Congo"),
    CD("CD", "180", "Congo, The Democratic Republic of the"),
    CK("CK", "184", "Cook Islands"),
    CR("CR", "188", "Costa Rica"),
    CI("CI", "384", "Cout d'Ivoire"),
    HR("HR", "191", "Croatia"),
    CU("CU", "192", "Cuba"),
    CY("CY", "196", "Cyprus"),
    CZ("CZ", "203", "Czech Republic"),
    DK("DK", "208", "Denmark"),
    DJ("DJ", "262", "Djibouti"),
    DM("DM", "212", "Dominica"),
    DO("DO", "214", "Dominican Republic"),
    EC("EC", "218", "Ecuador"),
    EG("EG", "818", "Egypt"),
    SV("SV", "222", "El Salvador"),
    GQ("GQ", "226", "Equatorial Guinea"),
    ER("ER", "232", "Eritrea"),
    EE("EE", "233", "Estonia"),
    ET("ET", "231", "Ethiopia"),
    FK("FK", "238", "Falkland Islands (Malvinas)"),
    FO("FO", "234", "Faroe Islands"),
    FJ("FJ", "242", "Fiji"),
    FI("FI", "246", "Finland"),
    FR("FR", "250", "France"),
    GF("GF", "254", "French Guiana"),
    PF("PF", "258", "French Polynesia"),
    GA("GA", "266", "Gabon"),
    GM("GM", "270", "Gambia"),
    GE("GE", "268", "Georgia"),
    DE("DE", "276", "Germany"),
    GH("GH", "288", "Ghana"),
    GI("GI", "292", "Gibraltar"),
    GR("GR", "300", "Greece"),
    GL("GL", "304", "Greenland"),
    GD("GD", "308", "Grenada"),
    GP("GP", "312", "Guadeloupe"),
    GU("GU", "316", "Guam"),
    GT("GT", "320", "Guatemala"),
    GN("GN", "324", "Guinea"),
    GW("GW", "624", "Guinea-Bissau"),
    GY("GY", "328", "Guyana"),
    HT("HT", "332", "Haiti"),
    VA("VA", "336", "Holy See (Vatican City State)"),
    HN("HN", "340", "Honduras"),
    HK("HK", "344", "Hong Kong"),
    HU("HU", "348", "Hungary"),
    IS("IS", "352", "Iceland"),
    IN("IN", "356", "India"),
    ID("ID", "360", "Indonesia"),
    IR("IR", "364", "Iran, Islamic Republic of"),
    IQ("IQ", "368", "Iraq"),
    IE("IE", "372", "Ireland"),
    IL("IL", "376", "Israel"),
    IT("IT", "380", "Italy"),
    JM("JM", "388", "Jamaica"),
    JP("JP", "392", "Japan"),
    JO("JO", "400", "Jordan"),
    KZ("KZ", "398", "Kazakhstan"),
    KE("KE", "404", "Kenya"),
    KI("KI", "296", "Kiribati"),
    KP("KP", "408", "Korea, Democratic People's Republic of"),
    KR("KR", "410", "Korea, Republic of"),
    KW("KW", "414", "Kuwait"),
    KG("KG", "417", "Kyrgyzstan"),
    LA("LA", "418", "Lao People's Democratic Republic"),
    LV("LV", "428", "Latvia"),
    LB("LB", "422", "Lebanon"),
    LS("LS", "426", "Lesotho"),
    LR("LR", "430", "Liberia"),
    LY("LY", "434", "Libyan Arab Jamahiriya"),
    LI("LI", "438", "Liechtenstein"),
    LT("LT", "440", "Lithuania"),
    LU("LU", "442", "Luxembourg"),
    MO("MO", "446", "Macao"),
    MK("MK", "807", "Macedonia, The Former Yugoslav Republic of"),
    MG("MG", "450", "Madagascar"),
    MW("MW", "454", "Malawi"),
    MY("MY", "458", "Malaysia"),
    MV("MV", "462", "Maldives"),
    ML("ML", "466", "Mali"),
    MT("MT", "470", "Malta"),
    MH("MH", "584", "Marshall Islands"),
    MQ("MQ", "474", "Martinique"),
    MR("MR", "478", "Mauritania"),
    MU("MU", "480", "Mauritius"),
    YT("YT", "175", "Mayotte"),
    MX("MX", "484", "Mexico"),
    FM("FM", "583", "Micronesia, Federated States of"),
    MD("MD", "498", "Moldova, Republic of"),
    MC("MC", "492", "Monaco"),
    MN("MN", "496", "Mongolia"),
    MS("MS", "500", "Montserrat"),
    MA("MA", "504", "Morocco"),
    MZ("MZ", "508", "Mozambique"),
    MM("MM", "104", "Myanmar"),
    NA("NA", "516", "Namibia"),
    NR("NR", "520", "Nauru"),
    NP("NP", "524", "Nepal"),
    NL("NL", "528", "Netherlands"),
    AN("AN", "530", "Netherlands Antilles"),
    NC("NC", "540", "New Caledonia"),
    NZ("NZ", "554", "New Zealand"),
    NI("NI", "558", "Nicaragua"),
    NE("NE", "562", "Niger"),
    NG("NG", "566", "Nigeria"),
    NU("NU", "570", "Niue"),
    NF("NF", "574", "Norfolk Island"),
    MP("MP", "580", "Northern Mariana Islands"),
    NO("NO", "578", "Norway"),
    OM("OM", "512", "Oman"),
    PK("PK", "586", "Pakistan"),
    PW("PW", "585", "Palau"),
    PS("PS", "275", "Palestinian Territory, Occupied"),
    PA("PA", "591", "Panama"),
    PG("PG", "598", "Papua New Guinea"),
    PY("PY", "600", "Paraguay"),
    PE("PE", "604", "Peru"),
    PH("PH", "608", "Philippines"),
    PN("PN", "612", "Pitcairn"),
    PL("PL", "616", "Poland"),
    PT("PT", "620", "Portugal"),
    PR("PR", "630", "Puerto Rico"),
    QA("QA", "634", "Qatar"),
    RE("RE", "638", "Reunion"),
    RO("RO", "642", "Romania"),
    RU("RU", "643", "Russian Federation"),
    RW("RW", "646", "Rwanda"),
    SH("SH", "654", "Saint Helena"),
    KN("KN", "659", "Saint Kitts and Nevis"),
    LC("LC", "662", "Saint Lucia"),
    PM("PM", "666", "Saint Pierre and Miquelon"),
    VC("VC", "670", "Saint Vincent and the Grenadines"),
    WS("WS", "882", "Samoa"),
    SM("SM", "674", "San Marino"),
    ST("ST", "678", "Sao Tome and Principe"),
    SA("SA", "682", "Saudi Arabia"),
    SN("SN", "704", "Senegal"),
    CS("CS", "891", "Serbia and Montenegro"),
    SC("SC", "690", "Seychelles"),
    SL("SL", "694", "Sierra Leone"),
    SG("SG", "702", "Singapore"),
    SK("SK", "703", "Slovakia"),
    SI("SI", "705", "Slovenia"),
    SB("SB", "090", "Solomon Islands"),
    SO("SO", "706", "Somalia"),
    ZA("ZA", "710", "South Africa"),
    GS("GS", "239", "South Georgia and the South Sandwich Islands"),
    ES("ES", "724", "Spain"),
    LK("LK", "144", "Sri Lanka"),
    SD("SD", "736", "Sudan"),
    SR("SR", "740", "Suriname"),
    SJ("SJ", "744", "Svalbard and Jan Mayen"),
    SZ("SZ", "748", "Swaziland"),
    SE("SE", "752", "Sweden"),
    CH("CH", "756", "Switzerland"),
    SY("SY", "760", "Syrian Arab Republic"),
    TW("TW", "158", "Taiwan, Province of China"),
    TJ("TJ", "762", "Tajikistan"),
    TZ("TZ", "834", "Tanzania, United Republic of"),
    TH("TH", "764", "Thailand"),
    TL("TL", "626", "Timor-Leste"),
    TG("TG", "768", "Togo"),
    TK("TK", "772", "Tokelau"),
    TO("TO", "776", "Tonga"),
    TT("TT", "780", "Trinidad and Tobago"),
    TN("TN", "788", "Tunisia"),
    TR("TR", "792", "Turkey"),
    TM("TM", "795", "Turkmenistan"),
    TC("TC", "796", "Turks and Caicos Islands"),
    TV("TV", "798", "Tuvalu"),
    UG("UG", "800", "Uganda"),
    UA("UA", "804", "Ukraine"),
    AE("AE", "784", "United Arab Emirates"),
    GB("GB", "826", "United Kingdom"),
    US("US", "840", "United States"),
    UM("UM", "581", "United States Minor Outlying Islands"),
    UY("UY", "858", "Uruguay"),
    UZ("UZ", "860", "Uzbekistan"),
    VU("VU", "548", "Vanuatu"),
    VE("VE", "862", "Venezuela"),
    VN("VN", "704", "Viet Nam"),
    VG("VG", "092", "Virgin Islands, British"),
    VI("VI", "850", "Virgin Islands, U.S."),
    WF("WF", "876", "Wallis and Futuna"),
    EH("EH", "732", "Western Sahara"),
    YE("YE", "887", "Yemen"),
    ZM("ZM", "894", "Zambia"),
    ZW("ZW", "716", "Zimbabwe"),
    UNKNOWN("XX", "000", "Unknown");

    private final String alpha2;
    private final String numeric;
    private final String displayName;

    CountryCode(String alpha2, String numeric, String displayName) {
        this.alpha2 = alpha2;
        this.numeric = numeric;
        this.displayName = displayName;
    }

    public static CountryCode fromCode(String code) {
        if (code == null)
            return UNKNOWN;
        for (CountryCode cc : values()) {
            if (cc.alpha2.equalsIgnoreCase(code) || cc.numeric.equals(code)) {
                return cc;
            }
        }
        return UNKNOWN;
    }
}
